services:
  postgres:
    restart: unless-stopped
    image: postgis/postgis:17-3.5-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
      - ./database/init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    healthcheck:
      test:  pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
  webserver:
    restart: unless-stopped
    build: ./app/backend
    env_file:
      - .env
    volumes:
      - uploads-volume:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
  webapp:
    restart: unless-stopped
    build:
      context: ./app/frontend/SocialSpot
      args:
        - VITE_API_URL=${VITE_API_URL}
    env_file:
      - .env
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/${NGINX_CONF}:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - webapp
      - webserver
volumes:
  pgdata:
  uploads-volume: